// GENERATED by scripts/sync-abi.mjs — do not edit by hand.
// Source: contracts/out/<Name>.sol/<Name>.json

export const PassportRegistryABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "attestor_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "SCORE_PRECISION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "actionCount",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "actionsOnDay",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentIdByDomain",
    "inputs": [
      {
        "name": "domain",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentIdByDomainHash",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentIdByOperator",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentsOf",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "attestor",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "canPerform",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "capability",
        "type": "string"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "ok",
        "type": "bool"
      },
      {
        "name": "reason",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "dayIndex",
    "inputs": [
      {
        "name": "timestamp",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getAgent",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "operator",
            "type": "address"
          },
          {
            "name": "owner",
            "type": "address"
          },
          {
            "name": "domain",
            "type": "string"
          },
          {
            "name": "metadataURI",
            "type": "string"
          },
          {
            "name": "registeredAt",
            "type": "uint64"
          },
          {
            "name": "active",
            "type": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAuthority",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "spendLimitPerDay",
            "type": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64"
          },
          {
            "name": "capabilityRoot",
            "type": "bytes32"
          },
          {
            "name": "maxActionsPerDay",
            "type": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCapabilities",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getReputation",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "total",
            "type": "uint32"
          },
          {
            "name": "success",
            "type": "uint32"
          },
          {
            "name": "failure",
            "type": "uint32"
          },
          {
            "name": "rejected",
            "type": "uint32"
          },
          {
            "name": "firstActionAt",
            "type": "uint64"
          },
          {
            "name": "lastActionAt",
            "type": "uint64"
          },
          {
            "name": "volumeHandled",
            "type": "uint256"
          },
          {
            "name": "logHead",
            "type": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasCapability",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "capability",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isExecutor",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "passportOf",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "agent",
        "type": "tuple",
        "components": [
          {
            "name": "operator",
            "type": "address"
          },
          {
            "name": "owner",
            "type": "address"
          },
          {
            "name": "domain",
            "type": "string"
          },
          {
            "name": "metadataURI",
            "type": "string"
          },
          {
            "name": "registeredAt",
            "type": "uint64"
          },
          {
            "name": "active",
            "type": "bool"
          }
        ]
      },
      {
        "name": "authority",
        "type": "tuple",
        "components": [
          {
            "name": "spendLimitPerDay",
            "type": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint64"
          },
          {
            "name": "capabilityRoot",
            "type": "bytes32"
          },
          {
            "name": "maxActionsPerDay",
            "type": "uint32"
          }
        ]
      },
      {
        "name": "reputation",
        "type": "tuple",
        "components": [
          {
            "name": "total",
            "type": "uint32"
          },
          {
            "name": "success",
            "type": "uint32"
          },
          {
            "name": "failure",
            "type": "uint32"
          },
          {
            "name": "rejected",
            "type": "uint32"
          },
          {
            "name": "firstActionAt",
            "type": "uint64"
          },
          {
            "name": "lastActionAt",
            "type": "uint64"
          },
          {
            "name": "volumeHandled",
            "type": "uint256"
          },
          {
            "name": "logHead",
            "type": "bytes32"
          }
        ]
      },
      {
        "name": "capabilities",
        "type": "string[]"
      },
      {
        "name": "score",
        "type": "uint32"
      },
      {
        "name": "ownerProof",
        "type": "uint8"
      },
      {
        "name": "ownerNullifier",
        "type": "bytes32"
      },
      {
        "name": "spendRemainingToday",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recentActions",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "components": [
          {
            "name": "agentId",
            "type": "uint256"
          },
          {
            "name": "outcome",
            "type": "uint8"
          },
          {
            "name": "timestamp",
            "type": "uint64"
          },
          {
            "name": "value",
            "type": "uint256"
          },
          {
            "name": "evidence",
            "type": "bytes32"
          },
          {
            "name": "kind",
            "type": "string"
          },
          {
            "name": "witness",
            "type": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerAgent",
    "inputs": [
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "domain",
        "type": "string"
      },
      {
        "name": "metadataURI",
        "type": "string"
      },
      {
        "name": "capabilities",
        "type": "string[]"
      },
      {
        "name": "spendLimitPerDay",
        "type": "uint256"
      },
      {
        "name": "maxActionsPerDay",
        "type": "uint32"
      },
      {
        "name": "expiresAt",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rejectAction",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "capability",
        "type": "string"
      },
      {
        "name": "value",
        "type": "uint256"
      },
      {
        "name": "evidence",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "actionIndex",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "remainingSpendToday",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scoreOf",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setActive",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "active",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAuthority",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "capabilities",
        "type": "string[]"
      },
      {
        "name": "spendLimitPerDay",
        "type": "uint256"
      },
      {
        "name": "maxActionsPerDay",
        "type": "uint32"
      },
      {
        "name": "expiresAt",
        "type": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setExecutor",
    "inputs": [
      {
        "name": "executor",
        "type": "address"
      },
      {
        "name": "allowed",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMetadataURI",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "metadataURI",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleAction",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "capability",
        "type": "string"
      },
      {
        "name": "value",
        "type": "uint256"
      },
      {
        "name": "outcome",
        "type": "uint8"
      },
      {
        "name": "evidence",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "actionIndex",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "spentOnDay",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ActionSettled",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "actionIndex",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "outcome",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "evidence",
        "type": "bytes32",
        "indexed": false
      },
      {
        "name": "kind",
        "type": "string",
        "indexed": false
      },
      {
        "name": "logHead",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentActiveSet",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "active",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AgentRegistered",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "domain",
        "type": "string",
        "indexed": false
      },
      {
        "name": "metadataURI",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AuthoritySet",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "spendLimitPerDay",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "maxActionsPerDay",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "capabilityRoot",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CapabilitySet",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "capability",
        "type": "string",
        "indexed": false
      },
      {
        "name": "granted",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExecutorSet",
    "inputs": [
      {
        "name": "executor",
        "type": "address",
        "indexed": true
      },
      {
        "name": "allowed",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MetadataUpdated",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "metadataURI",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReputationUpdated",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "score",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "total",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "success",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "failure",
        "type": "uint32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AgentInactive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AuthorityExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CapabilityNotGranted",
    "inputs": [
      {
        "name": "capability",
        "type": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "DailyActionsExceeded",
    "inputs": [
      {
        "name": "used",
        "type": "uint32"
      },
      {
        "name": "allowed",
        "type": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "DailySpendExceeded",
    "inputs": [
      {
        "name": "requested",
        "type": "uint256"
      },
      {
        "name": "remaining",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DomainTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyDomain",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotExecutor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OperatorTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnerNotHumanVerified",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownAgent",
    "inputs": []
  }
];

export const HumanhoodAttestorABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "attestor_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "attestor",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashAttestation",
    "inputs": [
      {
        "name": "att",
        "type": "tuple",
        "components": [
          {
            "name": "subject",
            "type": "address"
          },
          {
            "name": "kind",
            "type": "uint8"
          },
          {
            "name": "nullifierHash",
            "type": "bytes32"
          },
          {
            "name": "verifiedAt",
            "type": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64"
          },
          {
            "name": "appId",
            "type": "string"
          },
          {
            "name": "action",
            "type": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "humanhoodOf",
    "inputs": [
      {
        "name": "subject",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "kind",
            "type": "uint8"
          },
          {
            "name": "nullifierHash",
            "type": "bytes32"
          },
          {
            "name": "verifiedAt",
            "type": "uint64"
          },
          {
            "name": "appId",
            "type": "string"
          },
          {
            "name": "action",
            "type": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isHumanVerified",
    "inputs": [
      {
        "name": "subject",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nullifierFor",
    "inputs": [
      {
        "name": "subject",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nullifierOwner",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proofKindOf",
    "inputs": [
      {
        "name": "subject",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recordHumanhood",
    "inputs": [
      {
        "name": "att",
        "type": "tuple",
        "components": [
          {
            "name": "subject",
            "type": "address"
          },
          {
            "name": "kind",
            "type": "uint8"
          },
          {
            "name": "nullifierHash",
            "type": "bytes32"
          },
          {
            "name": "verifiedAt",
            "type": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64"
          },
          {
            "name": "appId",
            "type": "string"
          },
          {
            "name": "action",
            "type": "string"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rotateAttestor",
    "inputs": [
      {
        "name": "next",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AttestorRotated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HumanhoodRecorded",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "indexed": true
      },
      {
        "name": "nullifierHash",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "kind",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "recordedAt",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AttestationExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NullifierBoundToOther",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownProofKind",
    "inputs": []
  }
];

export const AgentNameRegistrarABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "parentName_",
        "type": "string"
      },
      {
        "name": "registry_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addr",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "addr",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      },
      {
        "name": "coinType",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentIdOfName",
    "inputs": [
      {
        "name": "full",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "allNodes",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "customTextKeys",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fullNameForLabel",
    "inputs": [
      {
        "name": "label",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getName",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "label",
            "type": "string"
          },
          {
            "name": "fullName",
            "type": "string"
          },
          {
            "name": "owner",
            "type": "address"
          },
          {
            "name": "target",
            "type": "address"
          },
          {
            "name": "agentId",
            "type": "uint256"
          },
          {
            "name": "registeredAt",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nameOfAddress",
    "inputs": [
      {
        "name": "a",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "namehash",
    "inputs": [
      {
        "name": "name",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "node",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "nodeForLabel",
    "inputs": [
      {
        "name": "label",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "parentName",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "parentNode",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerSubname",
    "inputs": [
      {
        "name": "label",
        "type": "string"
      },
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "target",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "node",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolveName",
    "inputs": [
      {
        "name": "full",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "label",
            "type": "string"
          },
          {
            "name": "fullName",
            "type": "string"
          },
          {
            "name": "owner",
            "type": "address"
          },
          {
            "name": "target",
            "type": "address"
          },
          {
            "name": "agentId",
            "type": "uint256"
          },
          {
            "name": "registeredAt",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reverseNode",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAddr",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      },
      {
        "name": "target",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setText",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      },
      {
        "name": "key",
        "type": "string"
      },
      {
        "name": "value",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "id",
        "type": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "text",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32"
      },
      {
        "name": "key",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AddrChanged",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "addr",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ParentNameSet",
    "inputs": [
      {
        "name": "parentName",
        "type": "string",
        "indexed": false
      },
      {
        "name": "parentNode",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReverseSet",
    "inputs": [
      {
        "name": "addr",
        "type": "address",
        "indexed": true
      },
      {
        "name": "node",
        "type": "bytes32",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SubnameRegistered",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "label",
        "type": "string",
        "indexed": false
      },
      {
        "name": "fullName",
        "type": "string",
        "indexed": false
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TextChanged",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "key",
        "type": "string",
        "indexed": true
      },
      {
        "name": "value",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidLabel",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NameTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoSuchName",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotNameOwner",
    "inputs": []
  }
];
