#!/usr/bin/env node
/**
 * Extracts the ABIs the JS side needs out of forge artifacts into a single
 * generated module. Run after every `forge build` so the SDK can never drift
 * from the deployed bytecode.
 */
import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const NAMES = ['PassportRegistry', 'HumanhoodAttestor', 'AgentNameRegistrar'];

const out = [
  '// GENERATED by scripts/sync-abi.mjs — do not edit by hand.',
  '// Source: contracts/out/<Name>.sol/<Name>.json',
  '',
];

for (const name of NAMES) {
  const artifactPath = join(root, 'contracts', 'out', `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  // Drop internal type metadata that bloats the bundle; viem does not need it.
  const abi = artifact.abi.map((entry) => JSON.parse(JSON.stringify(entry, (k, v) => (k === 'internalType' ? undefined : v))));
  out.push(`export const ${name}ABI = ${JSON.stringify(abi, null, 2)};`, '');
}

const target = join(root, 'packages', 'sdk', 'src', 'abi.js');
mkdirSync(dirname(target), {recursive: true});
writeFileSync(target, out.join('\n'));
console.log(`wrote ${target} (${NAMES.join(', ')})`);
